/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./theme/**/*.html", "./theme/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#c3c6cf",
        "tertiary": "#d6c3b7",
        "primary-fixed": "#dfe2eb",
        "error": "#ffb4ab",
        "on-primary": "#2d3137",
        "on-error": "#690005",
        "inverse-on-surface": "#313031",
        "outline-variant": "#45474b",
        "surface-container-low": "#1c1b1c",
        "on-tertiary-fixed": "#231a12",
        "on-surface": "#e5e2e2",
        "error-container": "#93000a",
        "inverse-primary": "#5b5e66",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#c2c7d0",
        "on-tertiary-fixed-variant": "#51443b",
        "tertiary-fixed-dim": "#d6c3b7",
        "tertiary-fixed": "#f3dfd2",
        "on-secondary-fixed": "#171c23",
        "on-secondary-container": "#b1b5bf",
        "on-primary-fixed-variant": "#43474e",
        "on-secondary": "#2c3138",
        "primary-container": "#0d1117",
        "outline": "#8f9095",
        "inverse-surface": "#e5e2e2",
        "on-background": "#e5e2e2",
        "primary": "#c3c6cf",
        "surface-container-highest": "#353435",
        "surface-container-lowest": "#0e0e0f",
        "surface-dim": "#131314",
        "surface": "#131314",
        "secondary-container": "#42474f",
        "secondary-fixed": "#dee2ec",
        "surface-variant": "#353435",
        "on-surface-variant": "#c6c6cb",
        "primary-fixed-dim": "#c3c6cf",
        "surface-bright": "#3a3939",
        "on-tertiary": "#3a2e26",
        "on-primary-fixed": "#181c22",
        "surface-container": "#201f20",
        "on-secondary-fixed-variant": "#42474f",
        "background": "#131314",
        "on-tertiary-container": "#897a6f",
        "on-primary-container": "#797d85",
        "surface-container-high": "#2a2a2a",
        "tertiary-container": "#180f08",
        "secondary": "#c2c7d0"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "container-max": "1012px",
        "margin-sm": "16px",
        "margin-md": "32px",
        "gutter": "24px",
        "margin-lg": "64px"
      },
      fontFamily: {
        "headline-md": ["Geist"],
        "label-mono": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "headline-lg": ["Geist"],
        "body-md": ["Inter"],
        "headline-xl": ["Geist"],
        "headline-lg-mobile": ["Geist"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-mono": ["14px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.3", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
